# Generated by Django 6.0.4 on 2026-04-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='internships.application'),
        ),
    ]
